begin;

set local lock_timeout = '5s';
set local statement_timeout = '30s';

-- Keep the active two-argument rendered-card flow from 0096. Only the public
-- fallback metadata changes; ownership, moderation and private-media checks
-- remain unchanged.
create or replace function public.create_public_post_share(p_post uuid, p_preview_ref text)
returns uuid language plpgsql security definer set search_path = public as $$
declare p record; share_id uuid;
begin
  if p_preview_ref !~ '^r2://share-cards/' or split_part(p_preview_ref, '/', 4) <> auth.uid()::text then
    raise exception 'Invalid share-card reference.' using errcode = '22023';
  end if;
  select id, user_id, body into p from public.posts
   where id = p_post and user_id = auth.uid() and moderation_state = 'visible';
  if not found then
    raise exception 'That post cannot be shared by this account.' using errcode = '42501';
  end if;
  insert into public.public_shares(owner_id, post_id, title, description, preview_image_url, preview_image_ref)
  values (auth.uid(), p.id, left(coalesce(nullif(trim(p.body), ''), 'A win from Mantle'), 160),
          'A progress update shared with permission from Mantle.', null, p_preview_ref)
  returning id into share_id;
  return share_id;
end;
$$;

revoke execute on function public.create_public_post_share(uuid, text) from public, anon;
grant execute on function public.create_public_post_share(uuid, text) to authenticated, service_role;

-- Descriptions were always generated by the creator RPC. Match only the two
-- historical templates and leave revoked, expired and custom text untouched.
update public.public_shares s
set description = case
  when s.description = 'Shared from AccountAbility' then 'Shared from Mantle'
  when s.description = 'A progress update shared with permission from AccountAbility.'
    then 'A progress update shared with permission from Mantle.'
  else s.description
end
where s.revoked_at is null
  and s.expires_at > now()
  and s.description in (
    'Shared from AccountAbility',
    'A progress update shared with permission from AccountAbility.'
  );

-- The old title can also be user-authored, so only rename it when the linked
-- post body is blank (the exact condition that caused the RPC fallback) and
-- the description is one of the known system templates after normalization.
update public.public_shares s
set title = 'A win from Mantle'
from public.posts p
where p.id = s.post_id
  and s.revoked_at is null
  and s.expires_at > now()
  and s.title = 'A win from AccountAbility'
  and nullif(trim(p.body), '') is null
  and s.description in (
    'Shared from Mantle',
    'A progress update shared with permission from Mantle.'
  );

commit;
